2025-10-03 18:52:20,908 - INFO - ==================================================
2025-10-03 18:52:20,908 - INFO - EXPERIMENT CONFIGURATION
2025-10-03 18:52:20,908 - INFO - ==================================================
2025-10-03 18:52:20,908 - INFO - Model Name          : MobileNetV1
2025-10-03 18:52:20,908 - INFO - Config File         : configs/pcad_config.yaml
2025-10-03 18:52:20,908 - INFO - Train Data          : /scratch/ehdmenezes//tiny-imagenet-200/train
2025-10-03 18:52:20,909 - INFO - Validation Data     : /scratch/ehdmenezes//tiny-imagenet-200/val
2025-10-03 18:52:20,909 - INFO - model_params        : {'num_classes': 200}
2025-10-03 18:52:20,909 - INFO - train_params        : {'epochs': 10, 'batch_size': 64, 'learning_rate': 0.001}
2025-10-03 18:52:20,909 - INFO - inference_params    : {'batch_size': 128}
2025-10-03 18:52:20,909 - INFO - ==================================================
2025-10-03 18:52:20,957 - INFO - Semente aleatória para esta execução foi fixada em: 52
2025-10-03 18:52:21,258 - ERROR - Ocorreu um erro fatal durante a execução do projeto: Mapeamento para o modelo 'MobileNetV1' não encontrado.
Traceback (most recent call last):
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/main.py", line 64, in main
    trained_model_path = train_pipeline.run_training(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/pipelines/train_pipeline.py", line 88, in run_training
    model = get_model(model_name, config['num_classes']).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/pipelines/train_pipeline.py", line 42, in get_model
    raise ValueError(f"Mapeamento para o modelo '{model_name}' não encontrado.")
ValueError: Mapeamento para o modelo 'MobileNetV1' não encontrado.
