/scratch/ehdmenezes/venv_cnn_perf/lib/python3.11/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
/scratch/ehdmenezes/venv_cnn_perf/lib/python3.11/site-packages/torch/cuda/__init__.py:61: FutureWarning: The pynvml package is deprecated. Please install nvidia-ml-py instead. If you did not install pynvml directly, please report this to the maintainers of the package that installed pynvml for you.
  import pynvml  # type: ignore[import]
2025-10-03 18:53:33,740 - INFO - ==================================================
INFO:VGG16_epochs_10_bs_64:==================================================
2025-10-03 18:53:33,740 - INFO - EXPERIMENT CONFIGURATION
INFO:VGG16_epochs_10_bs_64:EXPERIMENT CONFIGURATION
2025-10-03 18:53:33,740 - INFO - ==================================================
INFO:VGG16_epochs_10_bs_64:==================================================
2025-10-03 18:53:33,740 - INFO - Model Name          : VGG16
INFO:VGG16_epochs_10_bs_64:Model Name          : VGG16
2025-10-03 18:53:33,740 - INFO - Config File         : configs/pcad_config.yaml
INFO:VGG16_epochs_10_bs_64:Config File         : configs/pcad_config.yaml
2025-10-03 18:53:33,740 - INFO - Train Data          : /scratch/ehdmenezes//tiny-imagenet-200/train
INFO:VGG16_epochs_10_bs_64:Train Data          : /scratch/ehdmenezes//tiny-imagenet-200/train
2025-10-03 18:53:33,740 - INFO - Validation Data     : /scratch/ehdmenezes//tiny-imagenet-200/val
INFO:VGG16_epochs_10_bs_64:Validation Data     : /scratch/ehdmenezes//tiny-imagenet-200/val
2025-10-03 18:53:33,740 - INFO - model_params        : {'num_classes': 200}
INFO:VGG16_epochs_10_bs_64:model_params        : {'num_classes': 200}
2025-10-03 18:53:33,741 - INFO - train_params        : {'epochs': 10, 'batch_size': 64, 'learning_rate': 0.001}
INFO:VGG16_epochs_10_bs_64:train_params        : {'epochs': 10, 'batch_size': 64, 'learning_rate': 0.001}
2025-10-03 18:53:33,741 - INFO - inference_params    : {'batch_size': 128}
INFO:VGG16_epochs_10_bs_64:inference_params    : {'batch_size': 128}
2025-10-03 18:53:33,741 - INFO - ==================================================
INFO:VGG16_epochs_10_bs_64:==================================================
2025-10-03 18:53:33,761 - INFO - Semente aleatória para esta execução foi fixada em: 42
INFO:VGG16_epochs_10_bs_64:Semente aleatória para esta execução foi fixada em: 42
2025-10-03 18:53:34,062 - ERROR - Ocorreu um erro fatal durante a execução do projeto: Mapeamento para o modelo 'VGG16' não encontrado.
Traceback (most recent call last):
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/main.py", line 64, in main
    trained_model_path = train_pipeline.run_training(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/pipelines/train_pipeline.py", line 88, in run_training
    model = get_model(model_name, config['num_classes']).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/pipelines/train_pipeline.py", line 42, in get_model
    raise ValueError(f"Mapeamento para o modelo '{model_name}' não encontrado.")
ValueError: Mapeamento para o modelo 'VGG16' não encontrado.
ERROR:VGG16_epochs_10_bs_64:Ocorreu um erro fatal durante a execução do projeto: Mapeamento para o modelo 'VGG16' não encontrado.
Traceback (most recent call last):
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/main.py", line 64, in main
    trained_model_path = train_pipeline.run_training(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/pipelines/train_pipeline.py", line 88, in run_training
    model = get_model(model_name, config['num_classes']).to(device)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/users/ehdmenezes/CNNs-Performance-Analysis/src/pipelines/train_pipeline.py", line 42, in get_model
    raise ValueError(f"Mapeamento para o modelo '{model_name}' não encontrado.")
ValueError: Mapeamento para o modelo 'VGG16' não encontrado.
